version: '3.8'
services:
  app: 
    build: . # a contaner image is built from the Dockerfile in the current directory
    volumes:
      - .:/usr/src/app # bind mount the current directory to /usr/src/app
      - /usr/src/app/node_modules # exclude the node_modules directory from the bind mount
    environment:
      - PORT=3000 # set the PORT env variable to 3000

  nginx: # name of the service
    image: nginx:latest # use the latest version of the nginx image
    ports:
      - "8080:80" # bind port 8080 on the host to port 80 on the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # bind mount the nginx.conf file to /etc/nginx/nginx.conf
    depends_on:
      - app # start the app service before the nginx service
