version: '3.8'

services:
  node-service:
    build: ./docker/api
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: books_db
      DB_ROOT_PASSWORD: password
      PORT: 3000
    depends_on:
      - db
    networks:
      - mynetwork
    deploy:
      replicas: 3

  db:
    image: mariadb:latest
    container_name: challenge3-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: books_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
      
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service
    networks:
      - mynetwork

networks:
  mynetwork:
